In [3]:
import numpy as np

In [4]:
l=[1,2,3,4,23,1,3,3]

In [5]:
a=np.array(l)

In [6]:
a

array([ 1,  2,  3,  4, 23,  1,  3,  3])

In [7]:
a.view

<function ndarray.view>

In [8]:
a.mean

<function ndarray.mean>

In [9]:
a.mean()

5.0

In [10]:
 a

array([ 1,  2,  3,  4, 23,  1,  3,  3])

In [11]:
b=a[::2]

In [12]:
b

array([ 1,  3, 23,  3])

In [13]:
b[:]=12

In [14]:
a

array([12,  2, 12,  4, 12,  1, 12,  3])

In [15]:
b

array([12, 12, 12, 12])

In [16]:
np.array(a) - np.array(b)

ValueError: operands could not be broadcast together with shapes (8,) (4,) 